import { useEffect, useState } from 'react';
import { api } from '../services/api';

type Phase = 'picking' | 'generating' | 'quizzing' | 'results';

interface Card { id: string; title: string; source_type: string; summary: string | null; }
interface Question {
  id: string;
  question_type: 'multiple_choice' | 'short_answer';
  question: string;
  options: string[] | null;
  correct_answer: string;
  explanation: string | null;
}
interface Quiz { id: string; title: string; questions: Question[]; }

const sourceIcons: Record<string, string> = {
  article: '📄', youtube: '▶️', podcast: '🎙️', pdf: '📑',
  note: '📝', wikipedia: '🌐', tiktok: '🎵', other: '📎',
};

export default function ReviewMode() {
  const [phase, setPhase] = useState<Phase>('picking');
  const [cards, setCards] = useState<Card[]>([]);
  const [search, setSearch] = useState('');
  const [loadingCards, setLoadingCards] = useState(true);
  const [selectedCard, setSelectedCard] = useState<Card | null>(null);
  const [quiz, setQuiz] = useState<Quiz | null>(null);
  const [currentQ, setCurrentQ] = useState(0);
  const [selected, setSelected] = useState('');
  const [shortAnswer, setShortAnswer] = useState('');
  const [showAnswer, setShowAnswer] = useState(false);
  const [answers, setAnswers] = useState<{ correct: boolean; question: string; given: string; expected: string }[]>([]);
  const [error, setError] = useState('');

  useEffect(() => {
    api.cards.list().then((data: any) => {
      setCards(data.cards || []);
      setLoadingCards(false);
    }).catch(() => setLoadingCards(false));
  }, []);

  const filtered = cards.filter(c =>
    !search || c.title.toLowerCase().includes(search.toLowerCase())
  );

  const startQuiz = async (card: Card) => {
    setSelectedCard(card);
    setError('');
    setPhase('generating');
    try {
      const existing: Quiz[] = await api.quizzes.list(card.id);
      const q = existing.length > 0 ? existing[0] : await api.quizzes.generate(card.id);
      if (!q.questions || q.questions.length === 0) {
        setError('Could not generate quiz questions for this content.');
        setPhase('picking');
        return;
      }
      setQuiz(q);
      setCurrentQ(0);
      setAnswers([]);
      setSelected('');
      setShortAnswer('');
      setShowAnswer(false);
      setPhase('quizzing');
    } catch (err: any) {
      setError(err.message || 'Failed to load quiz');
      setPhase('picking');
    }
  };

  const submitAnswer = () => {
    if (!quiz) return;
    const q = quiz.questions[currentQ];
    const given = q.question_type === 'multiple_choice' ? selected : shortAnswer.trim();
    if (!given) return;
    const correct = given.toLowerCase().trim() === q.correct_answer.toLowerCase().trim();
    setAnswers(prev => [...prev, { correct, question: q.question, given, expected: q.correct_answer }]);
    setShowAnswer(true);
  };

  const nextQuestion = () => {
    if (!quiz) return;
    if (currentQ + 1 >= quiz.questions.length) {
      setPhase('results');
    } else {
      setCurrentQ(q => q + 1);
      setSelected('');
      setShortAnswer('');
      setShowAnswer(false);
    }
  };

  const restart = () => {
    setPhase('picking');
    setQuiz(null);
    setSelectedCard(null);
    setAnswers([]);
    setError('');
  };

  // ── Picking phase ────────────────────────────────────────────────────────────
  if (phase === 'picking') {
    return (
      <div style={{ display: 'flex', flexDirection: 'column', height: '100%' }}>
        <div className="page-header">
          <h1 className="page-title">🧠 Review & Quiz</h1>
        </div>
        <div style={{ padding: '24px 32px', flex: 1, overflowY: 'auto' }}>
          <p style={{ color: 'var(--text-secondary)', marginBottom: 20 }}>
            Pick a card to quiz yourself on. Existing quizzes load instantly; new ones are generated by AI.
          </p>

          {error && <p style={{ color: 'var(--error)', marginBottom: 16 }}>{error}</p>}

          <input
            className="form-input"
            placeholder="Search cards..."
            value={search}
            onChange={e => setSearch(e.target.value)}
            style={{ marginBottom: 20, maxWidth: 400 }}
          />

          {loadingCards ? (
            <div className="loading-state"><div className="loading-spinner" /></div>
          ) : filtered.length === 0 ? (
            <div className="empty-state">
              <div className="empty-icon">📚</div>
              <h3>No cards yet</h3>
              <p>Save some content first, then come back to quiz yourself.</p>
            </div>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 8, maxWidth: 700 }}>
              {filtered.map(card => (
                <div
                  key={card.id}
                  onClick={() => startQuiz(card)}
                  style={{
                    display: 'flex', alignItems: 'center', gap: 12,
                    padding: '14px 18px', borderRadius: 'var(--radius-lg)',
                    border: '1px solid var(--border)', background: 'var(--bg-card)',
                    cursor: 'pointer', transition: 'border-color 0.15s, background 0.15s',
                  }}
                  onMouseEnter={e => (e.currentTarget.style.borderColor = 'var(--primary)')}
                  onMouseLeave={e => (e.currentTarget.style.borderColor = 'var(--border)')}
                >
                  <span style={{ fontSize: '1.4rem' }}>{sourceIcons[card.source_type] || '📎'}</span>
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <div style={{ fontWeight: 600, fontSize: '0.95rem', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                      {card.title}
                    </div>
                    {card.summary && (
                      <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginTop: 2, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                        {card.summary}
                      </div>
                    )}
                  </div>
                  <span style={{ fontSize: '0.8rem', color: 'var(--primary)', whiteSpace: 'nowrap' }}>Quiz →</span>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    );
  }

  // ── Generating phase ─────────────────────────────────────────────────────────
  if (phase === 'generating') {
    return (
      <div style={{ display: 'flex', flexDirection: 'column', height: '100%', alignItems: 'center', justifyContent: 'center' }}>
        <div className="loading-spinner" style={{ marginBottom: 20 }} />
        <p style={{ color: 'var(--text-secondary)' }}>Generating quiz for "{selectedCard?.title}"...</p>
      </div>
    );
  }

  // ── Quizzing phase ───────────────────────────────────────────────────────────
  if (phase === 'quizzing' && quiz) {
    const q = quiz.questions[currentQ];
    const progress = ((currentQ) / quiz.questions.length) * 100;

    return (
      <div style={{ display: 'flex', flexDirection: 'column', height: '100%' }}>
        <div className="page-header">
          <button className="btn btn-ghost btn-sm" onClick={restart}>← Back</button>
          <h1 className="page-title" style={{ fontSize: '1rem', margin: 0, flex: 1, paddingLeft: 16 }}>
            {selectedCard?.title}
          </h1>
          <span style={{ color: 'var(--text-secondary)', fontSize: '0.85rem' }}>
            {currentQ + 1} / {quiz.questions.length}
          </span>
        </div>

        {/* Progress bar */}
        <div style={{ height: 3, background: 'var(--border)' }}>
          <div style={{ height: '100%', width: `${progress}%`, background: 'var(--primary)', transition: 'width 0.3s' }} />
        </div>

        <div style={{ flex: 1, overflowY: 'auto', padding: '40px 32px', maxWidth: 680, width: '100%', margin: '0 auto' }}>
          <div style={{ marginBottom: 32 }}>
            <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 12 }}>
              {q.question_type === 'multiple_choice' ? 'Multiple Choice' : 'Short Answer'}
            </div>
            <h2 style={{ fontSize: '1.2rem', fontWeight: 600, lineHeight: 1.5, margin: 0 }}>
              {q.question}
            </h2>
          </div>

          {q.question_type === 'multiple_choice' && q.options && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10, marginBottom: 24 }}>
              {q.options.map((opt, i) => {
                let bg = 'var(--bg-elevated)';
                let border = 'var(--border)';
                let color = 'var(--text-primary)';
                if (showAnswer) {
                  if (opt === q.correct_answer) { bg = '#1a3a2a'; border = '#4caf50'; color = '#4caf50'; }
                  else if (opt === selected && opt !== q.correct_answer) { bg = '#3a1a1a'; border = 'var(--error)'; color = 'var(--error)'; }
                } else if (opt === selected) {
                  border = 'var(--primary)';
                }
                return (
                  <button
                    key={i}
                    disabled={showAnswer}
                    onClick={() => setSelected(opt)}
                    style={{
                      padding: '14px 18px', borderRadius: 'var(--radius)', textAlign: 'left',
                      background: bg, border: `1px solid ${border}`, color,
                      cursor: showAnswer ? 'default' : 'pointer', fontSize: '0.95rem',
                      transition: 'all 0.15s',
                    }}
                  >
                    {opt}
                  </button>
                );
              })}
            </div>
          )}

          {q.question_type === 'short_answer' && (
            <div style={{ marginBottom: 24 }}>
              <input
                className="form-input"
                placeholder="Your answer..."
                value={shortAnswer}
                onChange={e => setShortAnswer(e.target.value)}
                disabled={showAnswer}
                onKeyDown={e => { if (e.key === 'Enter' && !showAnswer) submitAnswer(); }}
                style={{ width: '100%', fontSize: '1rem', padding: '12px 16px' }}
                autoFocus
              />
            </div>
          )}

          {showAnswer && q.explanation && (
            <div style={{
              padding: '16px 20px', borderRadius: 'var(--radius)', marginBottom: 24,
              background: 'var(--bg-elevated)', border: '1px solid var(--border)',
              fontSize: '0.9rem', color: 'var(--text-secondary)', lineHeight: 1.6,
            }}>
              <strong style={{ color: 'var(--text-primary)' }}>Explanation: </strong>{q.explanation}
            </div>
          )}

          {showAnswer && q.question_type === 'short_answer' && (
            <div style={{
              padding: '12px 16px', borderRadius: 'var(--radius)', marginBottom: 24,
              background: shortAnswer.trim().toLowerCase() === q.correct_answer.toLowerCase() ? '#1a3a2a' : '#3a1a1a',
              border: `1px solid ${shortAnswer.trim().toLowerCase() === q.correct_answer.toLowerCase() ? '#4caf50' : 'var(--error)'}`,
              fontSize: '0.9rem',
            }}>
              {shortAnswer.trim().toLowerCase() === q.correct_answer.toLowerCase()
                ? <span style={{ color: '#4caf50' }}>Correct!</span>
                : <span style={{ color: 'var(--error)' }}>Expected: <strong>{q.correct_answer}</strong></span>
              }
            </div>
          )}

          <div style={{ display: 'flex', gap: 12 }}>
            {!showAnswer && (
              <button
                className="btn btn-primary"
                onClick={submitAnswer}
                disabled={q.question_type === 'multiple_choice' ? !selected : !shortAnswer.trim()}
              >
                Check Answer
              </button>
            )}
            {showAnswer && (
              <button className="btn btn-primary" onClick={nextQuestion}>
                {currentQ + 1 >= quiz.questions.length ? 'See Results' : 'Next Question →'}
              </button>
            )}
          </div>
        </div>
      </div>
    );
  }

  // ── Results phase ────────────────────────────────────────────────────────────
  if (phase === 'results') {
    const score = answers.filter(a => a.correct).length;
    const total = answers.length;
    const pct = Math.round((score / total) * 100);

    return (
      <div style={{ display: 'flex', flexDirection: 'column', height: '100%' }}>
        <div className="page-header">
          <h1 className="page-title">🧠 Review & Quiz</h1>
        </div>
        <div style={{ flex: 1, overflowY: 'auto', padding: '40px 32px', maxWidth: 680, width: '100%', margin: '0 auto' }}>
          <div style={{ textAlign: 'center', marginBottom: 40 }}>
            <div style={{ fontSize: '4rem', marginBottom: 12 }}>
              {pct >= 80 ? '🎉' : pct >= 50 ? '💪' : '📖'}
            </div>
            <h2 style={{ fontSize: '2rem', margin: '0 0 8px' }}>
              {score} / {total}
            </h2>
            <p style={{ color: 'var(--text-secondary)', margin: 0 }}>
              {pct >= 80 ? 'Excellent recall!' : pct >= 50 ? 'Good effort — review the misses below.' : 'Keep studying — you\'ll get there.'}
            </p>
          </div>

          {answers.some(a => !a.correct) && (
            <div style={{ marginBottom: 32 }}>
              <h3 style={{ fontSize: '0.95rem', fontWeight: 600, marginBottom: 16, color: 'var(--text-secondary)' }}>
                Missed questions
              </h3>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
                {answers.filter(a => !a.correct).map((a, i) => (
                  <div key={i} style={{
                    padding: '14px 16px', borderRadius: 'var(--radius)',
                    background: 'var(--bg-elevated)', border: '1px solid var(--border)',
                  }}>
                    <div style={{ fontWeight: 600, marginBottom: 6, fontSize: '0.9rem' }}>{a.question}</div>
                    <div style={{ fontSize: '0.85rem', color: 'var(--error)' }}>Your answer: {a.given || '(blank)'}</div>
                    <div style={{ fontSize: '0.85rem', color: '#4caf50' }}>Correct: {a.expected}</div>
                  </div>
                ))}
              </div>
            </div>
          )}

          <div style={{ display: 'flex', gap: 12 }}>
            <button className="btn btn-primary" onClick={() => selectedCard && startQuiz(selectedCard)}>
              Retry Quiz
            </button>
            <button className="btn btn-secondary" onClick={restart}>
              Pick Another Card
            </button>
          </div>
        </div>
      </div>
    );
  }

  return null;
}
